### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by Faless** [eonpatapon/gnome-shell-extension-transmission-daemon#18]
Hi,
Hi!
I use transmission via https (it's behind proxy), sadly this extension does not provide SSL verification.
There are two ways of supporting it (but I didn't dig very much so excuse me if I'm wrong).
Simply adding:
    _httpSession.ssl_ca_file = "/PATH/TO/MY/CERT.pem";
after
    _httpSession = new Soup.SessionAsync(); 

Does the trick!

You can also use system-wide CAs https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--ssl-use-system-ca-file but the easier way should be adding an option in the extension preferences: "Verify SSL?" if left empty all certs are accepted, otherwise the path to certificate should be provided.

What do you think? I don't have lot of knowledge about shell extensions but I might have a look at how to implement the prefs thing if you don't have time for that.

Let me know,
                      Faless

**Comment by TheKevJames** [comment]
@Faless I've just taken over maintenance of this project on [my GitHub fork](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon) as well as the [extensions.gnome.org project](https://extensions.gnome.org/extension/365/transmission-daemon-indicator/).

As far as I understand, this feature has been added since you opened this issue. I verified myself with the latest deployed version against Gnome Shell 3.26 and found it was able to connect though SSL -- if you still experience this issue, I'd love to hear more; feel free to open an issue on [my fork](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon)
